#define NUM_FMU_VARIABLES 3

#define NUM_ONNX_INPUTS 2
#define NUM_ONNX_FMU_INPUTS 2
#define NUM_ONNX_OUTPUTS 1
#define NUM_ONNX_FMU_OUTPUTS 1
#define NUM_ONNX_STATES 0
#define NUM_ONNX_STATES_OUTPUTS 0

#define ONNX_INPUT_VALUE_REFERENCES 0, 0, 1, 1
#define ONNX_OUTPUT_VALUE_REFERENCES 0, 2
#define ONNX_STATE_OUTPUT_INDEXES 

#define ONNX_USE_TIME_INPUT false

#define ONNX_INPUT_NAME "args_0"
#define ONNX_OUTPUT_NAME "output_1"
#define ONNX_STATE_NAME ""
#define ONNX_TIME_INPUT_NAME ""
#define ONNX_FILENAME L"example.onnx"