#define NUM_FMU_VARIABLES 5

#define NUM_ONNX_INPUTS 4
#define NUM_ONNX_FMU_INPUTS 4
#define NUM_ONNX_OUTPUTS 1
#define NUM_ONNX_FMU_OUTPUTS 1
#define NUM_ONNX_STATES 0
#define NUM_ONNX_STATES_OUTPUTS 0
#define NUM_ONNX_STATE_INIT 0

#define ONNX_INPUT_VALUE_REFERENCES 0, 0, 1, 1, 2, 2, 3, 3
#define ONNX_OUTPUT_VALUE_REFERENCES 0, 4
#define ONNX_STATE_OUTPUT_INDEXES
#define ONNX_STATE_INIT_VALUE_REFERENCES

#define ONNX_USE_TIME_INPUT false

#define ONNX_INPUT_NAME "features"
#define ONNX_OUTPUT_NAME "prediction"
#define ONNX_STATE_NAME ""
#define ONNX_TIME_INPUT_NAME ""
#define ONNX_FILENAME L"rf_model.onnx"