name: Publish Release

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string

jobs:
  # publish to pypi
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    environment: release
    permissions:
        id-token: write
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: artifact
            path: dist
        - uses: pypa/gh-action-pypi-publish@release/v1
          with:                                             # Uncomment this line to publish to testpypi
             repository-url: https://test.pypi.org/legacy/   # Uncomment this line to publish to testpypi
  # create github release
  create_release:
    needs: publish_package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        with:
          tag_name: v${{ inputs.new-version }}
          release_name: Release v${{ inputs.new-version }}
          draft: false
          prerelease: false
  # merge release branch into main
  merge_into_release:
    uses: ./.github/workflows/_merge_into_release.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
