name: Push to release
run-name: Push to release by @${{ github.actor }}

on:
  push:
    branches:
      - release

concurrency:
  group: push-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_publish_documentation:
    uses: ./.github/workflows/_build_and_publish_documentation.yml

  # build the package artifacts
  build_package:
    needs: build_and_publish_documentation
    uses: ./.github/workflows/_build_package.yml
  # release package to pypi, github release, and merge into main
  publish_release:
    needs: build_package
    uses: ./.github/workflows/_publish_release.yml
    with:
      new_version: ${{ needs.bump_version.outputs.new-version }}
